export default {
  createAnimatedComponent: jest.fn(),
  addListener: jest.fn(),
  removeListeners: jest.fn(),
  startOperationBatch: jest.fn(),
  finishOperationBatch: jest.fn(),
  attachEvent: jest.fn(),
  detachEvent: jest.fn(),
  getValue: jest.fn(),
  setWaitingForIdentifier: jest.fn(),
  unsetWaitingForIdentifier: jest.fn(),
  setAnimatedNodeValue: jest.fn(),
  setAnimatedNodeOffset: jest.fn(),
  flattenAnimatedNodeOffset: jest.fn(),
  extractAnimatedNodeOffset: jest.fn(),
  connectAnimatedNodes: jest.fn(),
  disconnectAnimatedNodes: jest.fn(),
  startAnimatingNode: jest.fn(),
  stopAnimation: jest.fn(),
  setAnimatedNodeThreshold: jest.fn(),
};
